name: Weekly issue metrics
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    steps:
    - name: Get dates for last week
      shell: bash
      run: |
        ##########################################################
        # Create report for the previous week
        ##########################################################
        # Get the current date
        current_date=$(date +'%Y-%m-%d')
        # Calculate the start of the previous week (last Sunday)
        start_of_week=$(date -d "last-sunday - 1 week" +'%Y-%m-%d')
        # Calculate the end of the previous week (last Saturday)
        end_of_week=$(date -d "last-saturday" +'%Y-%m-%d')

        echo "$start_of_week..$end_of_week"
        echo "prev_week=$start_of_week..$end_of_week" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool for issues and PRs opened last week
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'mikaelacaron/Basic-Car-Maintenance created:${{ env.prev_week }}'

    - name: Create issue for opened issues and PRs last week
      uses: peter-evans/create-issue-from-file@v5
      with:
          title: Weekly issue metrics report for opened issues and PRs
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: mikaelacaron
          labels: weekly-report
    
    - name: Run issue-metrics tool for issues and PRs closed last week
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'mikaelacaron/Basic-Car-Maintenance closed:${{ env.prev_week }}'

    - name: Create issue for closed issues and prs
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Weekly issue metrics report for closed issues and prs
        content-filepath: ./issue_metrics.md
        assignees: mikaelacaron
        labels: weekly-report
